### ISSUE TITLE
Regarding language 

### ISSUE THREAD

**Issue by arfatsonde** [anhquan99/LSB-with-AES#3]
Hello @anhquan99 need your help to change the language. Here the result is showing in Vietnam language. How to change it to English.
Please guide. Result of encryption and decryption file

**Comment by arfatsonde** [comment]
Encryption is working but decryption is not working can you just have a look please @anhquan99

**Comment by anhquan99** [comment]
Hi @arfatsonde , can you send me the problem?

**Comment by anhquan99** [comment]
> Encryption is working but decryption is not working can you just have a look please @anhquan99

Hello @arfatsonde, I think you copied the "Result string Encrypt" from the encrypt AES. When you copy the result text it will not convert to the right format like UTF-8, UTF-16, ... I recommend you copy the byte number and check the "Is byte?" checkbox it will decrypt the right result.

**Comment by arfatsonde** [comment]
Can we connect to google meet once because tomorrow is my presentation I need to fixed it.
Please guide @anhquan99

**Comment by arfatsonde** [comment]
![image](https://user-images.githubusercontent.com/31978276/171785895-c381874b-d0b8-45e0-aacd-4f73a6f721fa.jpg)
Encryption is in veitnam language I need to do in english

**Comment by arfatsonde** [comment]
![Uploading image.jpg…]()
How to change in English @anhquan99

**Comment by arfatsonde** [comment]
![image](https://user-images.githubusercontent.com/31978276/171787012-7abd864e-7db8-4f71-b972-b0fa178bf42d.jpg)
How can we change it to English 
This is part of lsb extract

**Comment by anhquan99** [comment]
@arfatsonde if you extract the encrypted file it will not show the right format. So you should embed the text into the file and then extract it.

**Comment by arfatsonde** [comment]
@anhquan99 in analyse part we need to select same image it’s asking original image and watermark image.
Or we need to select different image

**Comment by arfatsonde** [comment]
![image](https://user-images.githubusercontent.com/31978276/171793878-9daf7336-293a-4208-a922-ed722ec35a28.jpg)
If selecting same image then it’s showing only single line in graph

**Comment by arfatsonde** [comment]
![Uploading image.jpg…]()

**Comment by arfatsonde** [comment]
![Uploading image.jpg…]()
@anhquan99

**Comment by anhquan99** [comment]
@arfatsonde yeah if it is the same image it will show only the red line because the red line is on the blue.
For the analyze the watermark image you should select the embedded image or the watermarked image. It should showing the red and the blue line near to each other

**Comment by arfatsonde** [comment]
@anhquan99 i have selected the original image and watermark image

**Comment by anhquan99** [comment]
I think you should put a lot of data in the message

**Comment by arfatsonde** [comment]
I need to put less data or more data @anhquan99

**Comment by anhquan99** [comment]
More. Sorry my bad English

**Comment by arfatsonde** [comment]
I will try and show you the output 
Right now my laptop is dead no charging @anhquan99

**Comment by arfatsonde** [comment]
@anhquan99  I have tried by putting lots of data but there is only one line. Can you guide please
![image](https://user-images.githubusercontent.com/31978276/171836180-32687911-ccab-43de-bcf6-cd2d7430a77b.jpg)
![Uploading image.jpg…]()

**Comment by arfatsonde** [comment]
![image](https://user-images.githubusercontent.com/31978276/171836329-2e5e62ae-a125-47cf-b3b4-3689029970e5.jpg)
@anhquan99

**Comment by anhquan99** [comment]
@arfatsonde Ah the red and yellow chart normally they don't change the blue one changes

**Comment by arfatsonde** [comment]
@anhquan99 there is no yellow colour. N there is no changes in all three graphs

**Comment by anhquan99** [comment]
Sorry i mean green in rgb

**Comment by anhquan99** [comment]
Hi @arfatsonde, I just push the sample files you can use for testing. I use https://loremipsum.io/ for generating string, I generate 50 paragraphs and it shows some differences with the audio file and you will hear the white noise. As for the image file, the LSB algorithms make little changes on the file so the analysis shows only the red line one is correct.

**Comment by arfatsonde** [comment]
@anhquan99  I have not performed audio part. Any audio file we can insert in it. Or some specific audio files. Can you guide.

**Comment by arfatsonde** [comment]
Can you share which file you have uploaded in audio @anhquan99

**Comment by anhquan99** [comment]
You should discover by your self

**Comment by arfatsonde** [comment]
@anhquan99  okay

**Comment by anhquan99** [comment]
@arfatsonde it is wav file

**Comment by arfatsonde** [comment]
@anhquan99 do you have any type of documentation/presentation of this project.

**Comment by anhquan99** [comment]
No I don't

**Comment by arfatsonde** [comment]
@anhquan99  I have selected wav file 
But it’s showing error as to small to water mark?

**Comment by arfatsonde** [comment]
![image](https://user-images.githubusercontent.com/31978276/172001193-7e076a5c-b40f-472d-9add-7f112a270d37.jpg)
@anhquan99

**Comment by anhquan99** [comment]
@arfatsonde this error sometimes happens but I don't know either the file or the algorithms is wrong you can debug on you visual studio

**Comment by arfatsonde** [comment]
I should debug lsb.audio or full project @anhquan99

**Comment by anhquan99** [comment]
You need to discover your self

**Comment by arfatsonde** [comment]
@anhquan99 thank you for helping me and your project was good. My professor liked it a lot😊.

**Comment by anhquan99** [comment]
@arfatsonde you are welcome my friend
